name: GitHub Stats Automation

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@v0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Move 3D SVG
        run: |
          mkdir -p stage
          if [ -d profile-3d-contrib ]; then cp profile-3d-contrib/*.svg stage/; fi

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./stage
          publish_branch: output
          commit_message: "Update 3D Profile Stats [skip ci]"
